{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum[1m])\r\n/\r\nrate(flask_http_request_duration_seconds_count[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(flask_http_requests_total)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(flask_http_requests_total[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}